// datalayer-artifact.ts — PURE builder for the SAFE "assistive dataLayer" artifact.
//
// SAFETY BY DESIGN: this produces ONE reference file (markdown) listing, per event,
// the exact dataLayer.push(...) the site needs, a plain-English "fires when", and a
// TODO/verify placement instruction. It does NOT locate or edit the developer's
// handlers/business logic — the human places each snippet and verifies. A .md file
// is intentional: it's obviously documentation, never auto-imported/run.
//
// No IO. Input = the proposal items already generated by buildImplementationProposal.

import type { ProposalItem } from '../measurement/implementation-proposal.ts';
import type { LocationSuggestion } from './datalayer-locator.ts';

// A markdown guide, not executable code — so it can never be bundled and fire on
// its own. The developer copies each snippet into the right handler themselves.
export const DATALAYER_ARTIFACT_PATH = 'ANALYTICS-DATALAYER.md';

export interface DataLayerArtifact {
  path: string;
  contents: string;
  eventCount: number;
}

// Plain-English "fires when" for the developer — derived from the event category,
// NOT by inspecting their code. Honest hints, never a located handler.
function firesWhen(category: ProposalItem['category'], eventName: string): string {
  switch (category) {
    case 'page':
      return 'a page loads';
    case 'form':
      return `the “${eventName}” form is submitted (after validation passes)`;
    case 'ecommerce':
      return `the “${eventName}” e-commerce step happens (e.g. add-to-cart, begin checkout, purchase)`;
    case 'conversion':
      return `the “${eventName}” conversion completes`;
    case 'engagement':
      return `the “${eventName}” interaction happens (e.g. a click or scroll)`;
    default:
      return `the “${eventName}” interaction happens`;
  }
}

// Where the developer should place it — a hint to THEIR handler, which only they
// can identify. The app never finds or edits it.
function placementHint(category: ProposalItem['category']): string {
  switch (category) {
    case 'page':
      return 'your page-load / route-change code (or rely on GTM’s All Pages trigger — often no code needed)';
    case 'form':
      return 'your form’s submit handler, AFTER validation succeeds (never before validation)';
    case 'ecommerce':
      return 'the handler for that e-commerce action (e.g. the add-to-cart / checkout button handler)';
    case 'conversion':
      return 'the code that runs when the conversion completes (e.g. the success / thank-you step)';
    case 'engagement':
      return 'the relevant click / scroll handler';
    default:
      return 'the relevant interaction handler';
  }
}

const HEADER =
  '# dataLayer event snippets — review & place\n\n' +
  'These are ready-to-use dataLayer pushes. Place each one in the matching action handler in your site and verify before relying on it. ' +
  'This file does not wire them up automatically.\n\n' +
  '> Each snippet must run at the moment the event actually happens — inside **your** form submit handler (after validation), button click handler, etc. ' +
  'This guide does **not** edit any of your existing code; you place each snippet yourself and confirm it fires (e.g. with GTM Preview or by logging `window.dataLayer`).\n>\n' +
  '> Any **SUGGESTED file** below is a best-effort guess from reading your repo to help you find the right place faster — **always verify it before placing**; the file was not modified.\n';

// Renders the best-effort location suggestion for one event. Always labelled
// verify-first; only ever names a real file the locator found (or "none found").
function renderSuggestion(s: LocationSuggestion): string {
  if (s.suggestedFile) {
    const alts = s.alternatives.length ? ` _Alternatives:_ ${s.alternatives.map((a) => `\`${a}\``).join(', ')}.` : '';
    return (
      `**SUGGESTED file:** \`${s.suggestedFile}\` _(${s.confidence} confidence — verify before placing)_ — ${s.locationHint}${alts}\n\n`
    );
  }
  return `**SUGGESTED file:** none found with confidence — ${s.locationHint}\n\n`;
}

export function buildDataLayerArtifact(items: ProposalItem[], suggestions: LocationSuggestion[] = []): DataLayerArtifact {
  const byName = new Map(suggestions.map((s) => [s.eventName, s]));
  const sections = items.map((item) => {
    const keyTag = item.isKeyEvent ? ' — _key event_' : '';
    const sug = byName.get(item.eventName);
    return (
      `## \`${item.eventName}\`${keyTag}\n\n` +
      `**Why:** ${item.explanation}\n\n` +
      `**Fires when:** ${firesWhen(item.category, item.eventName)}.\n\n` +
      `**TODO:** place this in ${placementHint(item.category)}, then **verify** it fires before relying on it.\n\n` +
      (sug ? renderSuggestion(sug) : '') +
      '```js\n' +
      `${item.dataLayerSnippet}\n` +
      '```'
    );
  });

  const contents = `${HEADER}\n---\n\n${sections.join('\n\n---\n\n')}\n`;
  return { path: DATALAYER_ARTIFACT_PATH, contents, eventCount: items.length };
}
